package PredictorToolkits;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;

/**
 *
 * @author Hoimin
 */
public class RedoxPotCalculator extends javax.swing.JFrame {

    /**
     * Creates new form RedoxPotCalculator
     */
    public RedoxPotCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRedoxPot = new javax.swing.JTextField();
        txt_Energy_A1 = new javax.swing.JTextField();
        txt_Energy_A2 = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        RefElectrode = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Redox Calculator");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jLabel1.setText("Redox Potential");

        jLabel2.setText("V");

        jLabel4.setText("G(Sol) of A(-)");

        jLabel5.setText("G(Sol) of A");

        jLabel8.setText("eV");

        jLabel9.setText("eV");

        txtRedoxPot.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_Energy_A1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_Energy_A2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        RefElectrode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCE", "NHE", "Fc/Fc+", "Ag/AgCl", "Ag/AgNO3", "Li/Li+", "Hg/Hg2Cl2" }));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("4.28 eV");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("4.43 eV");

        jLabel3.setText("SHE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(87, 87, 87)
                        .addComponent(txt_Energy_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(71, 71, 71)
                        .addComponent(txt_Energy_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addComponent(txtRedoxPot, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jRadioButton1)
                        .addGap(13, 13, 13)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RefElectrode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Energy_A1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Energy_A2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRedoxPot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefElectrode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculate)
                    .addComponent(btnClear)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txt_Energy_A1.setText("");
        txt_Energy_A2.setText("");
        txtRedoxPot.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        if (txt_Energy_A2.getText().equals("") || txt_Energy_A1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the G(Sol) values to calculate redox potential!");
        } else {
            float G1 = Float.parseFloat(txt_Energy_A1.getText());
            float G2 = Float.parseFloat(txt_Energy_A2.getText());
            float SHE = 0;
            if(jRadioButton1.isSelected()){
                SHE = (float) 4.28;
            }else if (jRadioButton2.isSelected()){
                SHE = (float) 4.43;
            }else{
                JOptionPane.showMessageDialog(null, "You should select SHE");
            }
            if (G2 > G1){
                JOptionPane.showMessageDialog(null, "G(Sol) for A should be larger than G(Sol) for A(-1)");
            }else{
                float G_Sol = G2-G1;
                if(RefElectrode.getSelectedObjects()[0].equals("NHE")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE));
                }else if(RefElectrode.getSelectedObjects()[0].equals("SCE")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.2412));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Fc/Fc+")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.721));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Ag/AgCl")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.197));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Ag/AgNO3")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.541));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Li/Li+")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-3.05));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Hg/Hg2Cl2")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.280));
                }
            }
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedoxPotCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedoxPotCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedoxPotCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedoxPotCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RedoxPotCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> RefElectrode;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txtRedoxPot;
    private javax.swing.JTextField txt_Energy_A1;
    private javax.swing.JTextField txt_Energy_A2;
    // End of variables declaration//GEN-END:variables
}
