package PredictorToolkits;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JOptionPane;

/**
 *
 * @author Hoimin
 */
public class RedoxPotCalculator extends javax.swing.JFrame {

    /**
     * Creates new form RedoxPotCalculator
     */
    public RedoxPotCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRedoxPot = new javax.swing.JTextField();
        txt_Energy_A1 = new javax.swing.JTextField();
        txt_Energy_A2 = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        RefElectrode = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Redox Calculator");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Redox Potential");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel2.setText("V");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel4.setText("G(Sol) of A(-)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel5.setText("G(Sol) of A");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel8.setText("eV");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel9.setText("eV");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        txtRedoxPot.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtRedoxPot, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 90, 30));

        txt_Energy_A1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_Energy_A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, 30));

        txt_Energy_A2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_Energy_A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 90, 30));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 60, -1));

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, -1));

        RefElectrode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SCE", "NHE", "Fc/Fc+", "Ag/AgCl", "Ag/AgNO3", "Li/Li+", "Hg/Hg2Cl2" }));
        getContentPane().add(RefElectrode, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("4.28 eV");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("4.43 eV");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        jLabel3.setText("SHE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 30, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txt_Energy_A1.setText("");
        txt_Energy_A2.setText("");
        txtRedoxPot.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        // TODO add your handling code here:
        if (txt_Energy_A2.getText().equals("") || txt_Energy_A1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the G(Sol) values to calculate redox potential!");
        } else {
            float G1 = Float.parseFloat(txt_Energy_A1.getText());
            float G2 = Float.parseFloat(txt_Energy_A2.getText());
            float SHE = 0;
            if(jRadioButton1.isSelected()){
                SHE = (float) 4.28;
            }else if (jRadioButton2.isSelected()){
                SHE = (float) 4.43;
            }else{
                JOptionPane.showMessageDialog(null, "You should select SHE");
            }
            if (G2 > G1){
                JOptionPane.showMessageDialog(null, "G(Sol) for A should be larger than G(Sol) for A(-1)");
            }else{
                float G_Sol = G2-G1;
                if(RefElectrode.getSelectedObjects()[0].equals("NHE")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE));
                }else if(RefElectrode.getSelectedObjects()[0].equals("SCE")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.2412));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Fc/Fc+")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.721));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Ag/AgCl")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.197));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Ag/AgNO3")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.541));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Li/Li+")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-3.05));
                }else if(RefElectrode.getSelectedObjects()[0].equals("Hg/Hg2Cl2")){
                    txtRedoxPot.setText(String.format("%.3f", G_Sol*(-1)-SHE-0.280));
                }
            }
        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedoxPotCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedoxPotCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedoxPotCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedoxPotCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RedoxPotCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> RefElectrode;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField txtRedoxPot;
    private javax.swing.JTextField txt_Energy_A1;
    private javax.swing.JTextField txt_Energy_A2;
    // End of variables declaration//GEN-END:variables
}
